/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.*;

import javax.swing.Timer;
import logs.LogSessao;
import model.Log;
import model.Usuario;

/**
 *
 * @author Escola
 */
public class FrmAtividade3_1 extends javax.swing.JFrame {

    private static int codUsuario;
    private static int pontuacao;
    private static String nome = "";
    static LogSessao logAtv31 = new LogSessao();
    Timer tempoSessao;

    /**
     * Creates new form FrmAtividade3_1
     */
    public FrmAtividade3_1(int codigo, LogSessao logHerdado) {
        initComponents();
        logHerdado.zeraLog();
        logAtv31 = logHerdado;
        codUsuario = codigo;

        tempoSessao = new javax.swing.Timer(1000, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                acaoTempoSessao();
            }
        });


        tempoSessao.start();
        Usuario conexao = new Usuario();

        pontuacao = conexao.mostrarPontuacao(codUsuario);
        lblPontos.setText("" + pontuacao);

        embaralharLibras();
        embaralharFigura();
    }
    List<String> libras = new ArrayList<String>();
    List<String> figura = new ArrayList<String>();
    String[] librasHover = new String[5];
    String[] librasClick = new String[5];
    int flagLibraClicada = 0;
    boolean flagLibraJaClicada = false;
    int vidas = 3;
    int[] flagFigurasJaClicadas = new int[5];
    String[] valorFigura = new String[5];
    String[] figuraSelec = new String[3];

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        descricao_atividades = new javax.swing.JLabel();
        descricao_atividade = new javax.swing.JLabel();
        btnAjuda = new javax.swing.JButton();
        lbl_vidas = new javax.swing.JLabel();
        lblCoracao1 = new javax.swing.JLabel();
        lblCoracao2 = new javax.swing.JLabel();
        lblCoracao3 = new javax.swing.JLabel();
        btnLibra1 = new javax.swing.JButton();
        btnFigura1 = new javax.swing.JButton();
        btnLibra2 = new javax.swing.JButton();
        btnLibra3 = new javax.swing.JButton();
        btnLibra4 = new javax.swing.JButton();
        btnFigura2 = new javax.swing.JButton();
        btnFigura3 = new javax.swing.JButton();
        btnFigura4 = new javax.swing.JButton();
        lblCerto1 = new javax.swing.JLabel();
        lblCerto2 = new javax.swing.JLabel();
        lblCerto3 = new javax.swing.JLabel();
        lblCerto4 = new javax.swing.JLabel();
        btnAvancar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblPontos = new javax.swing.JLabel();
        btnSelecNivel = new javax.swing.JButton();
        lbl_fundo3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        descricao_atividades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/atividades.png"))); // NOI18N
        getContentPane().add(descricao_atividades);
        descricao_atividades.setBounds(240, 80, 350, 70);

        descricao_atividade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensAtv3/descricao_atividade3.png"))); // NOI18N
        getContentPane().add(descricao_atividade);
        descricao_atividade.setBounds(140, 30, 790, 30);

        btnAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnAjudaN.png"))); // NOI18N
        btnAjuda.setBorderPainted(false);
        btnAjuda.setContentAreaFilled(false);
        btnAjuda.setFocusPainted(false);
        btnAjuda.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnAjudaC.png"))); // NOI18N
        btnAjuda.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnAjudaH.png"))); // NOI18N
        btnAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjudaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAjuda);
        btnAjuda.setBounds(1040, 30, 210, 160);

        lbl_vidas.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lbl_vidas.setForeground(new java.awt.Color(255, 255, 255));
        lbl_vidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/descricao_vidas.png"))); // NOI18N
        lbl_vidas.setToolTipText("");
        getContentPane().add(lbl_vidas);
        lbl_vidas.setBounds(710, 100, 100, 30);

        lblCoracao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vidas.png"))); // NOI18N
        getContentPane().add(lblCoracao1);
        lblCoracao1.setBounds(830, 90, 70, 60);

        lblCoracao2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vidas.png"))); // NOI18N
        getContentPane().add(lblCoracao2);
        lblCoracao2.setBounds(890, 90, 70, 60);

        lblCoracao3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vidas.png"))); // NOI18N
        getContentPane().add(lblCoracao3);
        lblCoracao3.setBounds(950, 90, 70, 60);

        btnLibra1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensAtv3/libras_boloN.png"))); // NOI18N
        btnLibra1.setBorderPainted(false);
        btnLibra1.setContentAreaFilled(false);
        btnLibra1.setFocusPainted(false);
        btnLibra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibra1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLibra1);
        btnLibra1.setBounds(90, 170, 307, 110);

        btnFigura1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensAtv3/figura_bolo.png"))); // NOI18N
        btnFigura1.setBorderPainted(false);
        btnFigura1.setContentAreaFilled(false);
        btnFigura1.setFocusPainted(false);
        btnFigura1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFigura1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnFigura1);
        btnFigura1.setBounds(520, 160, 420, 128);

        btnLibra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensAtv3/libras_boloN.png"))); // NOI18N
        btnLibra2.setBorderPainted(false);
        btnLibra2.setContentAreaFilled(false);
        btnLibra2.setFocusPainted(false);
        btnLibra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibra2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLibra2);
        btnLibra2.setBounds(90, 300, 307, 110);

        btnLibra3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensAtv3/libras_boloN.png"))); // NOI18N
        btnLibra3.setBorderPainted(false);
        btnLibra3.setContentAreaFilled(false);
        btnLibra3.setFocusPainted(false);
        btnLibra3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibra3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLibra3);
        btnLibra3.setBounds(90, 420, 307, 110);

        btnLibra4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensAtv3/libras_boloN.png"))); // NOI18N
        btnLibra4.setBorderPainted(false);
        btnLibra4.setContentAreaFilled(false);
        btnLibra4.setFocusPainted(false);
        btnLibra4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibra4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLibra4);
        btnLibra4.setBounds(90, 550, 307, 110);

        btnFigura2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensAtv3/figura_bolo.png"))); // NOI18N
        btnFigura2.setBorderPainted(false);
        btnFigura2.setContentAreaFilled(false);
        btnFigura2.setFocusPainted(false);
        btnFigura2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFigura2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnFigura2);
        btnFigura2.setBounds(520, 280, 420, 128);

        btnFigura3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensAtv3/figura_bolo.png"))); // NOI18N
        btnFigura3.setBorderPainted(false);
        btnFigura3.setContentAreaFilled(false);
        btnFigura3.setFocusPainted(false);
        btnFigura3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFigura3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnFigura3);
        btnFigura3.setBounds(520, 400, 410, 128);

        btnFigura4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensAtv3/figura_bolo.png"))); // NOI18N
        btnFigura4.setBorderPainted(false);
        btnFigura4.setContentAreaFilled(false);
        btnFigura4.setFocusPainted(false);
        btnFigura4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFigura4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnFigura4);
        btnFigura4.setBounds(510, 530, 420, 128);
        getContentPane().add(lblCerto1);
        lblCerto1.setBounds(830, 170, 120, 90);
        getContentPane().add(lblCerto2);
        lblCerto2.setBounds(830, 300, 120, 90);
        getContentPane().add(lblCerto3);
        lblCerto3.setBounds(830, 410, 120, 90);
        getContentPane().add(lblCerto4);
        lblCerto4.setBounds(830, 540, 120, 90);

        btnAvancar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnAvancarN.png"))); // NOI18N
        btnAvancar.setBorderPainted(false);
        btnAvancar.setContentAreaFilled(false);
        btnAvancar.setFocusPainted(false);
        btnAvancar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnAvancarC.png"))); // NOI18N
        btnAvancar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnAvançarH.png"))); // NOI18N
        btnAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvancarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAvancar);
        btnAvancar.setBounds(980, 490, 240, 180);

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnSairPeqN.png"))); // NOI18N
        btnSair.setBorder(null);
        btnSair.setBorderPainted(false);
        btnSair.setContentAreaFilled(false);
        btnSair.setFocusPainted(false);
        btnSair.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnSairPeqC.png"))); // NOI18N
        btnSair.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnSairPeqH.png"))); // NOI18N
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(20, 10, 100, 90);

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(0), "Pontuação", 0, 0, new java.awt.Font("Trebuchet MS", 1, 18), new java.awt.Color(255, 255, 255)), null)); // NOI18N
        jPanel1.setOpaque(false);

        lblPontos.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        lblPontos.setForeground(new java.awt.Color(204, 255, 255));
        lblPontos.setText("0");
        jPanel1.add(lblPontos);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(1070, 200, 180, 100);

        btnSelecNivel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnSelecNivelN.png"))); // NOI18N
        btnSelecNivel.setBorder(null);
        btnSelecNivel.setBorderPainted(false);
        btnSelecNivel.setContentAreaFilled(false);
        btnSelecNivel.setFocusPainted(false);
        btnSelecNivel.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnSelecNivelC.png"))); // NOI18N
        btnSelecNivel.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnSelecNivelH.png"))); // NOI18N
        btnSelecNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecNivelActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelecNivel);
        btnSelecNivel.setBounds(1100, 340, 130, 100);

        lbl_fundo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoNivel1.png"))); // NOI18N
        getContentPane().add(lbl_fundo3);
        lbl_fundo3.setBounds(0, 0, 1290, 720);

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjudaActionPerformed
        // TODO add your handling code here:
        JdiAjuda ajuda = new JdiAjuda(this, rootPaneCheckingEnabled, 10);
        ajuda.setModal(true);
        ajuda.setVisible(true);
    }//GEN-LAST:event_btnAjudaActionPerformed

    private void btnLibra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibra1ActionPerformed
        // TODO add your handling code here:

        if (flagLibraClicada != 1) {

            flagLibraJaClicada = true;
            figuraSelec[1] = librasClick[1];

            btnLibra1.setIcon(new javax.swing.ImageIcon(getClass().getResource(librasClick[1])));
            btnLibra1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource(librasClick[1])));

            switch (flagLibraClicada) {
                case 2:
                    btnLibra2.setIcon(new javax.swing.ImageIcon(getClass().getResource(libras.get(1))));
                    btnLibra2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource(librasHover[2])));
                    break;

                case 3:
                    btnLibra3.setIcon(new javax.swing.ImageIcon(getClass().getResource(libras.get(2))));
                    btnLibra3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource(librasHover[3])));
                    break;

                case 4:

                    btnLibra4.setIcon(new javax.swing.ImageIcon(getClass().getResource(libras.get(3))));
                    btnLibra4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource(librasHover[4])));
                    break;

            }

            flagLibraClicada = 1;

        } else {
        }

    }//GEN-LAST:event_btnLibra1ActionPerformed

    private void btnFigura1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFigura1ActionPerformed
        // TODO add your handling code here:

        if (flagLibraJaClicada == true) {
            if (flagFigurasJaClicadas[1] == 0) {
                figuraSelec[2] = figura.get(0);

                if (compararLibraFigura(figuraSelec[1], figuraSelec[2])) {
                    pontuacao = pontuacao + 300;
                    lblPontos.setText("" + pontuacao);
                    lblCerto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/certo.png")));
                    flagFigurasJaClicadas[1] = 1;
                    JdiMensagens msg = new JdiMensagens(this, rootPaneCheckingEnabled, "A figura está correta!", "Parabéns!", "");
                    msg.setModal(true);
                    msg.setVisible(true);


                    logAtv31.setAcertos(logAtv31.getAcertos() + 1);
                    logAtv31.setPontosGanhos(logAtv31.getPontosGanhos() + 300);
                    logAtv31.setPontosTotais(logAtv31.getPontosTotais() + 300);








                    this.finalizaAtividade();
                } else {
                    vidas = vidas - 1;
                    switch (vidas) {
                        case 2:
                            lblCoracao3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/perdeuvida.png")));
                            break;
                        case 1:
                            lblCoracao3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/perdeuvida.png")));
                            lblCoracao2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/perdeuvida.png")));
                            break;
                        case 0:
                            lblCoracao3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/perdeuvida.png")));
                            lblCoracao2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/perdeuvida.png")));
                            lblCoracao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/perdeuvida.png")));
                            break;
                    }

                    JdiMensagens msg = new JdiMensagens(this, rootPaneCheckingEnabled, "Oh não, a figura está errada!", "Tente novamente!", "");
                    msg.setModal(true);
                    msg.setVisible(true);
                    logAtv31.setErros(logAtv31.getErros() + 1);
                    logAtv31.setPontosPerdidos(logAtv31.getPontosPerdidos() + 50);
                    logAtv31.setPontosTotais(logAtv31.getPontosTotais() - 50);

                    logAtv31.setVidasPerdidas(logAtv31.getVidasPerdidas() + 1);



                    pontuacao = pontuacao - 50;
                    if (pontuacao <= 0) {
                        pontuacao = 0;
                    }
                    lblPontos.setText("" + pontuacao);
                    lblCerto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/errado.png")));

                    if (vidas == 0) {
                        JdiMensagens msg2 = new JdiMensagens(this, rootPaneCheckingEnabled, "Oh não! Você perdeu todas suas vidas...", "Pratique mais a sua memória, e tente novamente!", "Na próxima você consegue!");
                        msg2.setModal(true);
                        msg2.setVisible(true);





                        FrmNivel3_1 telaNivel = new FrmNivel3_1(codUsuario, logAtv31);
                        telaNivel.setVisible(true);

                        this.dispose();

                    }

                }
            } else {
            }
        } else {
            JdiMensagens msg = new JdiMensagens(this, rootPaneCheckingEnabled, "Selecione primeiro uma palavra em Libras!", "", "");
            msg.setModal(true);
            msg.setVisible(true);

        }


    }//GEN-LAST:event_btnFigura1ActionPerformed

    private void btnLibra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibra2ActionPerformed
        // TODO add your handling code here:
        if (flagLibraClicada != 2) {

            flagLibraJaClicada = true;
            figuraSelec[1] = librasClick[2];

            btnLibra2.setIcon(new javax.swing.ImageIcon(getClass().getResource(librasClick[2])));
            btnLibra2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource(librasClick[2])));

            switch (flagLibraClicada) {
                case 1:
                    btnLibra1.setIcon(new javax.swing.ImageIcon(getClass().getResource(libras.get(0))));
                    btnLibra1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource(librasHover[1])));
                    break;

                case 3:
                    btnLibra3.setIcon(new javax.swing.ImageIcon(getClass().getResource(libras.get(2))));
                    btnLibra3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource(librasHover[3])));
                    break;

                case 4:

                    btnLibra4.setIcon(new javax.swing.ImageIcon(getClass().getResource(libras.get(3))));
                    btnLibra4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource(librasHover[4])));
                    break;

            }

            flagLibraClicada = 2;

        } else {
        }


    }//GEN-LAST:event_btnLibra2ActionPerformed

    private void btnLibra3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibra3ActionPerformed
        // TODO add your handling code here:

        if (flagLibraClicada != 3) {

            flagLibraJaClicada = true;
            figuraSelec[1] = librasClick[3];

            btnLibra3.setIcon(new javax.swing.ImageIcon(getClass().getResource(librasClick[3])));
            btnLibra3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource(librasClick[3])));

            switch (flagLibraClicada) {
                case 2:
                    btnLibra2.setIcon(new javax.swing.ImageIcon(getClass().getResource(libras.get(1))));
                    btnLibra2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource(librasHover[2])));
                    break;

                case 1:
                    btnLibra1.setIcon(new javax.swing.ImageIcon(getClass().getResource(libras.get(0))));
                    btnLibra1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource(librasHover[1])));
                    break;

                case 4:

                    btnLibra4.setIcon(new javax.swing.ImageIcon(getClass().getResource(libras.get(3))));
                    btnLibra4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource(librasHover[4])));
                    break;

            }

            flagLibraClicada = 3;

        } else {
        }
    }//GEN-LAST:event_btnLibra3ActionPerformed

    private void btnLibra4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibra4ActionPerformed
        // TODO add your handling code here:

        if (flagLibraClicada != 4) {

            flagLibraJaClicada = true;
            figuraSelec[1] = librasClick[4];

            btnLibra4.setIcon(new javax.swing.ImageIcon(getClass().getResource(librasClick[4])));
            btnLibra4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource(librasClick[4])));

            switch (flagLibraClicada) {
                case 2:
                    btnLibra2.setIcon(new javax.swing.ImageIcon(getClass().getResource(libras.get(1))));
                    btnLibra2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource(librasHover[2])));
                    break;

                case 1:
                    btnLibra1.setIcon(new javax.swing.ImageIcon(getClass().getResource(libras.get(0))));
                    btnLibra1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource(librasHover[1])));
                    break;

                case 3:

                    btnLibra3.setIcon(new javax.swing.ImageIcon(getClass().getResource(libras.get(2))));
                    btnLibra3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource(librasHover[3])));
                    break;

            }

            flagLibraClicada = 4;

        } else {
        }
    }//GEN-LAST:event_btnLibra4ActionPerformed

    private void btnFigura2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFigura2ActionPerformed
        // TODO add your handling code here:

        if (flagLibraJaClicada == true) {
            if (flagFigurasJaClicadas[2] == 0) {
                figuraSelec[2] = figura.get(1);

                if (compararLibraFigura(figuraSelec[1], figuraSelec[2])) {
                    pontuacao = pontuacao + 300;
                    lblPontos.setText("" + pontuacao);
                    lblCerto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/certo.png")));
                    flagFigurasJaClicadas[2] = 1;
                    JdiMensagens msg = new JdiMensagens(this, rootPaneCheckingEnabled, "A figura está correta!", "Parabéns!", "");
                    msg.setModal(true);
                    msg.setVisible(true);
                    logAtv31.setAcertos(logAtv31.getAcertos() + 1);
                    logAtv31.setPontosGanhos(logAtv31.getPontosGanhos() + 300);
                    logAtv31.setPontosTotais(logAtv31.getPontosTotais() + 300);

                    this.finalizaAtividade();
                } else {
                    vidas = vidas - 1;
                    switch (vidas) {
                        case 2:
                            lblCoracao3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/perdeuvida.png")));
                            break;
                        case 1:
                            lblCoracao3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/perdeuvida.png")));
                            lblCoracao2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/perdeuvida.png")));
                            break;
                        case 0:
                            lblCoracao3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/perdeuvida.png")));
                            lblCoracao2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/perdeuvida.png")));
                            lblCoracao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/perdeuvida.png")));
                            break;
                    }

                    JdiMensagens msg = new JdiMensagens(this, rootPaneCheckingEnabled, "Oh não, a figura está errada!", "Tente novamente!", "");
                    msg.setModal(true);
                    msg.setVisible(true);
                    logAtv31.setErros(logAtv31.getErros() + 1);
                    logAtv31.setPontosPerdidos(logAtv31.getPontosPerdidos() + 50);
                    logAtv31.setPontosTotais(logAtv31.getPontosTotais() - 50);

                    logAtv31.setVidasPerdidas(logAtv31.getVidasPerdidas() + 1);
                    pontuacao = pontuacao - 50;
                    if (pontuacao <= 0) {
                        pontuacao = 0;
                    }
                    lblPontos.setText("" + pontuacao);
                    lblCerto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/errado.png")));

                    if (vidas == 0) {
                        JdiMensagens msg2 = new JdiMensagens(this, rootPaneCheckingEnabled, "Oh não! Você perdeu todas suas vidas...", "Pratique mais a sua memória, e tente novamente!", "Na próxima você consegue!");
                        msg2.setModal(true);
                        msg2.setVisible(true);



                        FrmNivel3_1 telaNivel = new FrmNivel3_1(codUsuario, logAtv31);
                        telaNivel.setVisible(true);

                        this.dispose();

                    }

                }
            } else {
            }
        } else {
            JdiMensagens msg = new JdiMensagens(this, rootPaneCheckingEnabled, "Selecione primeiro uma palavra em Libras!", "", "");
            msg.setModal(true);
            msg.setVisible(true);
        }
    }//GEN-LAST:event_btnFigura2ActionPerformed

    private void btnFigura3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFigura3ActionPerformed
        // TODO add your handling code here:
        if (flagLibraJaClicada == true) {
            if (flagFigurasJaClicadas[3] == 0) {
                figuraSelec[2] = figura.get(2);

                if (compararLibraFigura(figuraSelec[1], figuraSelec[2])) {
                    pontuacao = pontuacao + 300;
                    lblPontos.setText("" + pontuacao);
                    lblCerto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/certo.png")));
                    flagFigurasJaClicadas[3] = 1;
                    JdiMensagens msg = new JdiMensagens(this, rootPaneCheckingEnabled, "A figura está correta!", "Parabéns!", "");
                    msg.setModal(true);
                    msg.setVisible(true);
                    logAtv31.setAcertos(logAtv31.getAcertos() + 1);
                    logAtv31.setPontosGanhos(logAtv31.getPontosGanhos() + 300);
                    logAtv31.setPontosTotais(logAtv31.getPontosTotais() + 300);

                    this.finalizaAtividade();
                } else {
                    vidas = vidas - 1;
                    switch (vidas) {
                        case 2:
                            lblCoracao3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/perdeuvida.png")));
                            break;
                        case 1:
                            lblCoracao3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/perdeuvida.png")));
                            lblCoracao2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/perdeuvida.png")));
                            break;
                        case 0:
                            lblCoracao3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/perdeuvida.png")));
                            lblCoracao2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/perdeuvida.png")));
                            lblCoracao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/perdeuvida.png")));
                            break;
                    }

                    JdiMensagens msg = new JdiMensagens(this, rootPaneCheckingEnabled, "Oh não, a figura está errada!", "Tente novamente!", "");
                    msg.setModal(true);
                    msg.setVisible(true);
                    logAtv31.setErros(logAtv31.getErros() + 1);
                    logAtv31.setPontosPerdidos(logAtv31.getPontosPerdidos() + 50);
                    logAtv31.setPontosTotais(logAtv31.getPontosTotais() - 50);

                    logAtv31.setVidasPerdidas(logAtv31.getVidasPerdidas() + 1);
                    pontuacao = pontuacao - 50;
                    if (pontuacao <= 0) {
                        pontuacao = 0;
                    }
                    lblPontos.setText("" + pontuacao);
                    lblCerto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/errado.png")));

                    if (vidas == 0) {
                        JdiMensagens msg2 = new JdiMensagens(this, rootPaneCheckingEnabled, "Oh não! Você perdeu todas suas vidas...", "Pratique mais a sua memória, e tente novamente!", "Na próxima você consegue!");
                        msg2.setModal(true);
                        msg2.setVisible(true);



                        FrmNivel3_1 telaNivel = new FrmNivel3_1(codUsuario, logAtv31);
                        telaNivel.setVisible(true);

                        this.dispose();

                    }

                }
            } else {
            }
        } else {
            JdiMensagens msg = new JdiMensagens(this, rootPaneCheckingEnabled, "Selecione primeiro uma palavra em Libras!", "", "");
            msg.setModal(true);
            msg.setVisible(true);
        }
    }//GEN-LAST:event_btnFigura3ActionPerformed

    private void btnFigura4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFigura4ActionPerformed
        // TODO add your handling code here:

        if (flagLibraJaClicada == true) {
            if (flagFigurasJaClicadas[4] == 0) {
                figuraSelec[2] = figura.get(3);

                if (compararLibraFigura(figuraSelec[1], figuraSelec[2])) {
                    pontuacao = pontuacao + 300;
                    lblPontos.setText("" + pontuacao);
                    lblCerto4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/certo.png")));
                    flagFigurasJaClicadas[4] = 1;
                    JdiMensagens msg = new JdiMensagens(this, rootPaneCheckingEnabled, "A figura está correta!", "Parabéns!", "");
                    msg.setModal(true);
                    msg.setVisible(true);
                    logAtv31.setAcertos(logAtv31.getAcertos() + 1);
                    logAtv31.setPontosGanhos(logAtv31.getPontosGanhos() + 300);
                    logAtv31.setPontosTotais(logAtv31.getPontosTotais() + 300);

                    this.finalizaAtividade();
                } else {
                    vidas = vidas - 1;
                    switch (vidas) {
                        case 2:
                            lblCoracao3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/perdeuvida.png")));
                            break;
                        case 1:
                            lblCoracao3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/perdeuvida.png")));
                            lblCoracao2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/perdeuvida.png")));
                            break;
                        case 0:
                            lblCoracao3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/perdeuvida.png")));
                            lblCoracao2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/perdeuvida.png")));
                            lblCoracao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/perdeuvida.png")));
                            break;
                    }

                    JdiMensagens msg = new JdiMensagens(this, rootPaneCheckingEnabled, "Oh não, a figura está errada!", "Tente novamente!", "");
                    msg.setModal(true);
                    msg.setVisible(true);
                    logAtv31.setErros(logAtv31.getErros() + 1);
                    logAtv31.setPontosPerdidos(logAtv31.getPontosPerdidos() + 50);
                    logAtv31.setPontosTotais(logAtv31.getPontosTotais() - 50);

                    logAtv31.setVidasPerdidas(logAtv31.getVidasPerdidas() + 1);
                    pontuacao = pontuacao - 50;
                    if (pontuacao <= 0) {
                        pontuacao = 0;
                    }
                    lblPontos.setText("" + pontuacao);
                    lblCerto4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/errado.png")));

                    if (vidas == 0) {
                        JdiMensagens msg2 = new JdiMensagens(this, rootPaneCheckingEnabled, "Oh não! Você perdeu todas suas vidas...", "Pratique mais a sua memória, e tente novamente!", "Na próxima você consegue!");
                        msg2.setModal(true);
                        msg2.setVisible(true);



                        FrmNivel3_1 telaNivel = new FrmNivel3_1(codUsuario, logAtv31);
                        telaNivel.setVisible(true);

                        this.dispose();

                    }

                }
            } else {
            }
        } else {
            JdiMensagens msg = new JdiMensagens(this, rootPaneCheckingEnabled, "Selecione primeiro uma palavra em Libras!", "", "");
            msg.setModal(true);
            msg.setVisible(true);
        }
    }//GEN-LAST:event_btnFigura4ActionPerformed

    private void btnAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvancarActionPerformed
        // TODO add your handling code here:
        finalizaAvancar();
    }//GEN-LAST:event_btnAvancarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        gerarLogEncerrar();
    }//GEN-LAST:event_formWindowClosing

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        gerarLogEncerrar();
        tempoSessao.stop();
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnSelecNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecNivelActionPerformed
        // TODO add your handling code here:
        String nome = "";
        Usuario conectar = new Usuario();
        nome = conectar.nomeUsuarioCod(codUsuario);
        conectar.inserirPontuacao(codUsuario, pontuacao);
        gerarLogEncerrar();
        tempoSessao.stop();
        FrmTelaNivel telaNivel = new FrmTelaNivel(nome, codUsuario, logAtv31);
        telaNivel.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSelecNivelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAtividade3_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAtividade3_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAtividade3_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAtividade3_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrmAtividade3_1(codUsuario, logAtv31).setVisible(true);
            }
        });
    }

    public void acaoTempoSessao() {
        logAtv31.seg++;

        if (logAtv31.seg == 30) {
            gerarLogEncerrar();
        }


        if (logAtv31.seg == 60) {
            logAtv31.min++;
            logAtv31.seg = 0;
        }

        if (logAtv31.min == 60) {
            logAtv31.hor++;
        }

        if (logAtv31.hor > 99) {
            logAtv31.hor = 99;
        }



    }

    private void gerarLog() {
        Log salvarLog = new Log();

        salvarLog.gerarLogSessao("atv31", logAtv31);
        tempoSessao.stop();
    }

    private void gerarLogEncerrar() {
        Log salvarLog = new Log();

        Date dataSessao = new Date();

        SimpleDateFormat formatoData = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat formatoHora = new SimpleDateFormat("hh:mm:ss");

        logAtv31.setHoraFimSessao(formatoData.format(dataSessao) + " " + formatoHora.format(dataSessao));

        logAtv31.setPontuacaoTotalSessao(logAtv31.getPontosTotais() + logAtv31.getPontuacaoTotalSessao());
        logAtv31.setTempoSessao("" + logAtv31.hor + ":" + logAtv31.min + ":" + logAtv31.seg);
        tempoSessao.stop();


        salvarLog.gerarLogEncerrarSessao("atv31", logAtv31);

    }

    private void embaralharLibras() //Declaração do metodo embaralharMao, que é privado e não retorna nada (void), apenas executa o código dentro dele 
    {
        //populando o endereço das imagens estáticas das mãos dentro do arrayList libras
        libras.addAll(Arrays.asList("/imagensAtv3/libras_boloN.png", "/imagensAtv3/libras_gatoN.png", "/imagensAtv3/libras_patoN.png", "/imagensAtv3/libras_sollN.png"));

        Collections.shuffle(libras); //sorteia a ordem das imagens ESTÁTICAS que vão para os botões das mãos

        //JOptionPane.showMessageDialog(rootPane, libras.get(0).substring(27, 28));
        //AGORA É UMA COISA IMPORTANTE!!! Isso faz com que as imagens das mãos com mouse emcima (contorno amarelo)
        // e com o mouse clicando (contorno vermelho) sejam AS MESMAS das mãos ESTÁTICAS!
        //Irei explicar. As imagens das mãos neutras, ou sejas, normais, estáticas, foram sorteadas. Se usarmos
        //a propriedade "rolloverIcon" e "pressedIcon" via botão direito no botão, as imagens lá escolhidas são FIXAS
        //elas ficariam diferente das novas imagens neutras sorteadas!
        //Então, o jeito é ter um array que em cada posição, vai ter a imagem CORRETA, na mesma ORDEM, do que as mãos neutras já sorteadas!
        //o nome da imagem é super importante para isso. as letras neutras, estaticas, tem como nome,
        //por ex a letra A "letraa_n.png", e a letra U, "letrau_n.png".
        //Já as com borda amarela e vermelha, tem como extensão "letraa_a.png" e "letraa_v.png"
        // A ideia que eu tive foi, atribuir para o array que contem o endereço da imagem neutra sorteada,
        //até o underline, que contem o endereço pra carta certa. Após o underline, seria ou "a.png" para amarela
        //"v.png" para vermelha.
        //Daí usei o metodo substring, onde  o valor de (0, 24), vai pegar, caso seja a letra a sorteada
        // "/LetrasMenores_atv1/letraa_". Daí, depois disso, adiciono para a string, manualmente, a extensão apropriada
        // para qual tipo de imagem ela pertence! Seja com mouse emcima, amarela, ou mouse clicando, vermelha!
        librasHover[1] = libras.get(0).substring(0, 24) + "A.png";
        librasHover[2] = libras.get(1).substring(0, 24) + "A.png";
        librasHover[3] = libras.get(2).substring(0, 24) + "A.png";
        librasHover[4] = libras.get(3).substring(0, 24) + "A.png";

        librasClick[1] = libras.get(0).substring(0, 24) + "V.png";
        librasClick[2] = libras.get(1).substring(0, 24) + "V.png";
        librasClick[3] = libras.get(2).substring(0, 24) + "V.png";
        librasClick[4] = libras.get(3).substring(0, 24) + "V.png";

        //Colocando a imagem sorteada já em cada botão! Aqui é a imagem neutra
        btnLibra1.setIcon(new javax.swing.ImageIcon(getClass().getResource(libras.get(0))));
        btnLibra2.setIcon(new javax.swing.ImageIcon(getClass().getResource(libras.get(1))));
        btnLibra3.setIcon(new javax.swing.ImageIcon(getClass().getResource(libras.get(2))));
        btnLibra4.setIcon(new javax.swing.ImageIcon(getClass().getResource(libras.get(3))));

        // aqui a imagem de mouse por cima
        btnLibra1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource(librasHover[1])));
        btnLibra2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource(librasHover[2])));
        btnLibra3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource(librasHover[3])));
        btnLibra4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource(librasHover[4])));

        // e aqui, a imagem de mouse clicando
        btnLibra1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource(librasClick[1])));
        btnLibra2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource(librasClick[2])));
        btnLibra3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource(librasClick[3])));
        btnLibra4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource(librasClick[4])));

    }

    private boolean compararLibraFigura(String valorMao, String valorNuvem) //Declaração do metodo compararNuvemMao
    //QUE RETORNA TRUE OU FALSE. Ele recebe 2 parâmetro, o 1 seria o nuvemSelec[1], que tem o valor da mao
    //selecionada, e o 2 seria o nuvemSelec[2], que tem o valor da nuvem selecionada.
    {

        //Longa explicação agora! Os valores usados para comparação, são os próprios endereços das imagens.
        //O valor da mão, seria por exemplo: "/LetrasMenores_atv1/letrau_n.png"
        //Já o valor da nuvem, seria por exemplo: "/imagens/Uu.png"
        //como podem ver, são totalmente diferentes. Como comparar se são iguais?
        //Aí que o metodo .substring entra em ação.
        //Seria muito menos confuso se nossa amiga Mariana padronizasse o nome dos botões
        // da forma que eu pedi, desde o começo. Mas, como ficou tudo diferente e sem padrão,
        // isso ficou meio confuso.
        //A idéia é declarar, dentro do método, 2 strings que vão receber o SUBSTRING do valor da mão
        // e do valor da nuvem.
        String vlNvm, vlMao;

        //Agora é preciso atribuir a essas strings, o valor substring da mao e da nuvem.
        //O substring precisa por 2 numeros como parâmetro, .substring(numero1, numero2)
        //O primeiro numero seria, apartir de qual caractere, da esquerda para direita, seria selecionado.
        //O segundo numero, seria, a partir de qual caractere, a seleção do primeiro caractere, terminaria.
        //Ex, string C = Cilada;
        //C.substring(3,5);
        //Iria exibir apenas "ad". 3 letras são Cil, e, 5 letras, são Cilad.
        //Vai pegar entre o cil e o a, depois do Cilad. Equivale a "ad".
        //Então, os dois valores de mao e nuvem tem algo em comum: o nome em minúsculo equivalente ao tipo de letra que
        // a imagem pertence.
        //a jogada foi selecionar apenas essa letra em minúsculo, e usala como comparação!
        vlNvm = valorNuvem.substring(20, 24);
        //Resultaria, por ex, /imagens/U[u].png 

        vlMao = valorMao.substring(20, 24);
        //Resultaria , por ex, /LetrasMenores_atv1/letra[u]_n.png

        //Se o sorteio fosse esses dois exemplos e a invocação desse metodo usasse eles,
        // daria u da nuvem, e u da mão. Então, a comparação a seguir, seria igual e retornaria true o/
        if (vlNvm.equals(vlMao)) //if comparando se os valores das substrings obtidas são iguais
        {
            // caso sim, retorna true
            return true;
        } else {

            // caso não, retorna false
            return false;
        }
    }

    private void embaralharFigura() //Declaração do metodo embaralharMao, que é privado e não retorna nada (void), apenas executa o código dentro dele 
    {
        //populando o endereço das imagens estáticas das mãos dentro do arrayList libras
        figura.addAll(Arrays.asList("/imagensAtv3/figura_gato.png", "/imagensAtv3/figura_pato.png", "/imagensAtv3/figura_soll.png", "/imagensAtv3/figura_bolo.png"));

        Collections.shuffle(figura);

        btnFigura1.setIcon(new javax.swing.ImageIcon(getClass().getResource(figura.get(0))));
        btnFigura2.setIcon(new javax.swing.ImageIcon(getClass().getResource(figura.get(1))));
        btnFigura3.setIcon(new javax.swing.ImageIcon(getClass().getResource(figura.get(2))));
        btnFigura4.setIcon(new javax.swing.ImageIcon(getClass().getResource(figura.get(3))));

    }

    private void finalizaAvancar() {

        int aux = 0;




        Usuario conectar = new Usuario();
        nome = conectar.nomeUsuarioCod(codUsuario);

        aux = conectar.niveisLiberados(codUsuario);

        conectar.inserirPontuacao(codUsuario, pontuacao);



        gerarLogEncerrar();

        JdiDesempenhoAtividade stats = new JdiDesempenhoAtividade(this, rootPaneCheckingEnabled, logAtv31, pontuacao, 3);
        stats.setModal(true);
        stats.setVisible(true);
        FrmTelaNivel telaNivel = new FrmTelaNivel(nome, codUsuario, logAtv31);
        telaNivel.setVisible(true);
        this.dispose();
    }

    private void finalizaAtividade() {
        int aux = 0;
        for (int i = 1; i <= 4; i++) {
            if (flagFigurasJaClicadas[i] == 1) {
                aux = aux + 1;

            }

            if (aux == 4) {


                Usuario conectar = new Usuario();
                nome = conectar.nomeUsuarioCod(codUsuario);

                aux = conectar.niveisLiberados(codUsuario);

                conectar.inserirPontuacao(codUsuario, pontuacao);


                gerarLogEncerrar();

                JdiDesempenhoAtividade stats = new JdiDesempenhoAtividade(this, rootPaneCheckingEnabled, logAtv31, pontuacao, 3);
                stats.setModal(true);
                stats.setVisible(true);

                FrmTelaNivel telaNivel = new FrmTelaNivel(nome, codUsuario, logAtv31);
                telaNivel.setVisible(true);
                this.dispose();
            }

        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjuda;
    private javax.swing.JButton btnAvancar;
    private javax.swing.JButton btnFigura1;
    private javax.swing.JButton btnFigura2;
    private javax.swing.JButton btnFigura3;
    private javax.swing.JButton btnFigura4;
    private javax.swing.JButton btnLibra1;
    private javax.swing.JButton btnLibra2;
    private javax.swing.JButton btnLibra3;
    private javax.swing.JButton btnLibra4;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSelecNivel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel descricao_atividade;
    private javax.swing.JLabel descricao_atividades;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCerto1;
    private javax.swing.JLabel lblCerto2;
    private javax.swing.JLabel lblCerto3;
    private javax.swing.JLabel lblCerto4;
    private javax.swing.JLabel lblCoracao1;
    private javax.swing.JLabel lblCoracao2;
    private javax.swing.JLabel lblCoracao3;
    private javax.swing.JLabel lblPontos;
    private javax.swing.JLabel lbl_fundo3;
    private javax.swing.JLabel lbl_vidas;
    // End of variables declaration//GEN-END:variables
}
