/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import model.*;

/**
 *
 * @author Luiz
 */
public class FrmCadastro extends javax.swing.JFrame {

    //Classe de objetos do tipo Usuario
    Usuario user = new Usuario();

    public FrmCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCadNome = new javax.swing.JTextField();
        txtCadEmail = new javax.swing.JTextField();
        txtCadUsuario = new javax.swing.JTextField();
        txtCadSenha = new javax.swing.JPasswordField();
        txtCadConfSenha = new javax.swing.JPasswordField();
        lblNome = new javax.swing.JLabel();
        bntCadastrar = new javax.swing.JButton();
        lblImgCadNome2 = new javax.swing.JLabel();
        lblImgCadNome1 = new javax.swing.JLabel();
        lblConfirmeSenha = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblImgCadNome3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        lblSenha = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        btnRelatorio = new javax.swing.JButton();
        btnRanking = new javax.swing.JButton();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dudu Libras Ver. 1.0");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setUndecorated(true);
        getContentPane().setLayout(null);

        txtCadNome.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtCadNome.setForeground(new java.awt.Color(255, 255, 255));
        txtCadNome.setToolTipText("");
        txtCadNome.setBorder(null);
        txtCadNome.setCaretColor(new java.awt.Color(255, 255, 255));
        txtCadNome.setOpaque(false);
        getContentPane().add(txtCadNome);
        txtCadNome.setBounds(500, 110, 280, 40);

        txtCadEmail.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtCadEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtCadEmail.setBorder(null);
        txtCadEmail.setCaretColor(new java.awt.Color(255, 255, 255));
        txtCadEmail.setOpaque(false);
        getContentPane().add(txtCadEmail);
        txtCadEmail.setBounds(490, 170, 300, 40);

        txtCadUsuario.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtCadUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtCadUsuario.setBorder(null);
        txtCadUsuario.setCaretColor(new java.awt.Color(255, 255, 255));
        txtCadUsuario.setOpaque(false);
        getContentPane().add(txtCadUsuario);
        txtCadUsuario.setBounds(490, 230, 290, 40);

        txtCadSenha.setForeground(new java.awt.Color(255, 255, 255));
        txtCadSenha.setBorder(null);
        txtCadSenha.setCaretColor(new java.awt.Color(255, 255, 255));
        txtCadSenha.setOpaque(false);
        getContentPane().add(txtCadSenha);
        txtCadSenha.setBounds(490, 294, 300, 30);

        txtCadConfSenha.setForeground(new java.awt.Color(255, 255, 255));
        txtCadConfSenha.setBorder(null);
        txtCadConfSenha.setCaretColor(new java.awt.Color(255, 255, 255));
        txtCadConfSenha.setOpaque(false);
        txtCadConfSenha.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(txtCadConfSenha);
        txtCadConfSenha.setBounds(490, 380, 290, 30);

        lblNome.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setText("Nome");
        getContentPane().add(lblNome);
        lblNome.setBounds(260, 110, 110, 40);

        bntCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnCadastrarN.png"))); // NOI18N
        bntCadastrar.setBorderPainted(false);
        bntCadastrar.setContentAreaFilled(false);
        bntCadastrar.setDefaultCapable(false);
        bntCadastrar.setFocusPainted(false);
        bntCadastrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnCadastrarC.png"))); // NOI18N
        bntCadastrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnCadastrarH.png"))); // NOI18N
        bntCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(bntCadastrar);
        bntCadastrar.setBounds(830, 270, 270, 170);

        lblImgCadNome2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao_vazio.png"))); // NOI18N
        getContentPane().add(lblImgCadNome2);
        lblImgCadNome2.setBounds(470, 170, 333, 50);

        lblImgCadNome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao_vazio.png"))); // NOI18N
        getContentPane().add(lblImgCadNome1);
        lblImgCadNome1.setBounds(470, 110, 333, 50);

        lblConfirmeSenha.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblConfirmeSenha.setForeground(new java.awt.Color(255, 255, 255));
        lblConfirmeSenha.setText("<html><p>Confirmar<br>Senha</p></html>");
        getContentPane().add(lblConfirmeSenha);
        lblConfirmeSenha.setBounds(260, 350, 180, 80);

        lblUsuario.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("Usuário");
        getContentPane().add(lblUsuario);
        lblUsuario.setBounds(260, 230, 140, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao_vazio.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(470, 370, 330, 60);

        lblImgCadNome3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao_vazio.png"))); // NOI18N
        getContentPane().add(lblImgCadNome3);
        lblImgCadNome3.setBounds(470, 230, 330, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao_vazio.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(470, 290, 340, 50);

        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnVoltarN.png"))); // NOI18N
        btnVoltar.setToolTipText("Voltará para a janela anterior.");
        btnVoltar.setBorder(null);
        btnVoltar.setContentAreaFilled(false);
        btnVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVoltar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnVoltarC.png"))); // NOI18N
        btnVoltar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnVoltarH.png"))); // NOI18N
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar);
        btnVoltar.setBounds(230, 560, 180, 140);

        lblSenha.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(255, 255, 255));
        lblSenha.setText("Senha");
        getContentPane().add(lblSenha);
        lblSenha.setBounds(260, 290, 140, 40);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/dudu_libras.png"))); // NOI18N
        getContentPane().add(lblLogo);
        lblLogo.setBounds(440, 20, 320, 70);

        lblEmail.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email");
        getContentPane().add(lblEmail);
        lblEmail.setBounds(260, 170, 110, 40);

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnSairN.png"))); // NOI18N
        btnSair.setBorder(null);
        btnSair.setBorderPainted(false);
        btnSair.setContentAreaFilled(false);
        btnSair.setFocusPainted(false);
        btnSair.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnSairC.png"))); // NOI18N
        btnSair.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnSairH.png"))); // NOI18N
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(0, 540, 200, 170);

        btnRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnRelatN.png"))); // NOI18N
        btnRelatorio.setBorder(null);
        btnRelatorio.setBorderPainted(false);
        btnRelatorio.setContentAreaFilled(false);
        btnRelatorio.setFocusPainted(false);
        btnRelatorio.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnRelatC.png"))); // NOI18N
        btnRelatorio.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnRelatH.png"))); // NOI18N
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });
        getContentPane().add(btnRelatorio);
        btnRelatorio.setBounds(460, 540, 270, 190);

        btnRanking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnRankingN.png"))); // NOI18N
        btnRanking.setBorder(null);
        btnRanking.setBorderPainted(false);
        btnRanking.setContentAreaFilled(false);
        btnRanking.setFocusPainted(false);
        btnRanking.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnRankingC.png"))); // NOI18N
        btnRanking.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnRankingH.png"))); // NOI18N
        btnRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRankingActionPerformed(evt);
            }
        });
        getContentPane().add(btnRanking);
        btnRanking.setBounds(800, 540, 270, 190);

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundonovo.png"))); // NOI18N
        getContentPane().add(lblFundo);
        lblFundo.setBounds(0, 0, 1380, 720);

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void bntCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCadastrarActionPerformed
       //chama o metodo cadastrar da classe Usuario
        user.cadastar(txtCadNome.getText(), txtCadEmail.getText(), txtCadUsuario.getText(), String.valueOf(txtCadSenha.getPassword()), String.valueOf(txtCadConfSenha.getPassword()));
    }//GEN-LAST:event_bntCadastrarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
       
        
        FrmTelaOpcao telaOpc = new FrmTelaOpcao();
        telaOpc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:

       System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        // TODO add your handling code here:
        FrmRelatorio relat = new FrmRelatorio();
        relat.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnRelatorioActionPerformed

    private void btnRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRankingActionPerformed
        // ao clikar no botao ira abrir a tela de cadastro

        FrmRanking ranking = new FrmRanking();
        ranking.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnRankingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCadastro().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCadastrar;
    private javax.swing.JButton btnRanking;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblConfirmeSenha;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblImgCadNome1;
    private javax.swing.JLabel lblImgCadNome2;
    private javax.swing.JLabel lblImgCadNome3;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txtCadConfSenha;
    private javax.swing.JTextField txtCadEmail;
    private javax.swing.JTextField txtCadNome;
    private javax.swing.JPasswordField txtCadSenha;
    private javax.swing.JTextField txtCadUsuario;
    // End of variables declaration//GEN-END:variables
}
