/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;

import logs.LogSessao;
import model.Log;
import model.Usuario;

/**
 *
 * @author user
 */
public class FrmLogin extends javax.swing.JFrame {

    static LogSessao logAbstrato = new LogSessao();

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();

        Date dataSessao = new Date();



        SimpleDateFormat formatoData = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat formatoHora = new SimpleDateFormat("hh:mm:ss");




        logAbstrato.setHoraInicioSessao(formatoData.format(dataSessao) + " " + formatoHora.format(dataSessao));



    }
    int codigo;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDuduEscudo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        txtLogUsuario = new javax.swing.JTextField();
        txtCadSenha = new javax.swing.JPasswordField();
        lblLogUsuario = new javax.swing.JLabel();
        lblLogSenha = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setUndecorated(true);
        getContentPane().setLayout(null);

        lblDuduEscudo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/escudo.png"))); // NOI18N
        getContentPane().add(lblDuduEscudo);
        lblDuduEscudo.setBounds(740, 70, 280, 350);

        lblUsuario.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("Usuário");
        getContentPane().add(lblUsuario);
        lblUsuario.setBounds(80, 170, 150, 40);

        lblSenha.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(255, 255, 255));
        lblSenha.setText("Senha");
        getContentPane().add(lblSenha);
        lblSenha.setBounds(80, 260, 150, 40);

        txtLogUsuario.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtLogUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtLogUsuario.setToolTipText("");
        txtLogUsuario.setBorder(null);
        txtLogUsuario.setCaretColor(new java.awt.Color(255, 255, 255));
        txtLogUsuario.setOpaque(false);
        txtLogUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLogUsuarioKeyPressed(evt);
            }
        });
        getContentPane().add(txtLogUsuario);
        txtLogUsuario.setBounds(260, 170, 300, 40);

        txtCadSenha.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtCadSenha.setForeground(new java.awt.Color(255, 255, 255));
        txtCadSenha.setBorder(null);
        txtCadSenha.setCaretColor(new java.awt.Color(255, 255, 255));
        txtCadSenha.setOpaque(false);
        txtCadSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadSenhaActionPerformed(evt);
            }
        });
        txtCadSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCadSenhaKeyPressed(evt);
            }
        });
        getContentPane().add(txtCadSenha);
        txtCadSenha.setBounds(260, 260, 300, 40);

        lblLogUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao_vazio.png"))); // NOI18N
        getContentPane().add(lblLogUsuario);
        lblLogUsuario.setBounds(240, 160, 370, 60);

        lblLogSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao_vazio.png"))); // NOI18N
        getContentPane().add(lblLogSenha);
        lblLogSenha.setBounds(240, 250, 370, 60);

        btnEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnJogarN.png"))); // NOI18N
        btnEntrar.setBorder(null);
        btnEntrar.setBorderPainted(false);
        btnEntrar.setContentAreaFilled(false);
        btnEntrar.setFocusPainted(false);
        btnEntrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnJogarC.png"))); // NOI18N
        btnEntrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnJogarH.png"))); // NOI18N
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        btnEntrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnEntrarKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnEntrarKeyTyped(evt);
            }
        });
        getContentPane().add(btnEntrar);
        btnEntrar.setBounds(330, 320, 220, 190);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnVoltarN.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnVoltarC.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnVoltarH.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 330, 190, 180);

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnSairN.png"))); // NOI18N
        btnSair.setBorder(null);
        btnSair.setBorderPainted(false);
        btnSair.setContentAreaFilled(false);
        btnSair.setFocusPainted(false);
        btnSair.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnSairC.png"))); // NOI18N
        btnSair.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnSairH.png"))); // NOI18N
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(0, 540, 200, 170);

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundonovo.png"))); // NOI18N
        getContentPane().add(lblFundo);
        lblFundo.setBounds(0, 0, 1380, 720);

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        Usuario user = new Usuario();
        //caso o usuario e senha existirem no banco a tela de niveis sera aberta
        if (user.logar(txtLogUsuario.getText(), String.valueOf(txtCadSenha.getPassword())) == true) {

            codigo = user.codigoUsuario(txtLogUsuario.getText(), String.valueOf(txtCadSenha.getPassword()));

            Log iniciarLog = new Log();
            int codLog = 0;
            codLog = iniciarLog.iniciarLogSessao(codigo, logAbstrato.getHoraInicioSessao());

            logAbstrato.setCodigoLog(codLog);



            FrmTelaNivel telaNivel;
            telaNivel = new FrmTelaNivel(user.nomeUsuario(txtLogUsuario.getText()), codigo, logAbstrato);
            telaNivel.setVisible(true);
            this.dispose();

        } else {
            
            JdiMensagens msg = new JdiMensagens(this, rootPaneCheckingEnabled, "Senha e/ou usuário inválido(s)!", "", "");
            msg.setModal(true);
            msg.setVisible(true);
            txtCadSenha.setText("");
            txtLogUsuario.setText("");
        }


    }//GEN-LAST:event_btnEntrarActionPerformed

    private void txtCadSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadSenhaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        FrmTelaOpcao telaopcao = new FrmTelaOpcao();
        telaopcao.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnEntrarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnEntrarKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntrarKeyTyped

    private void btnEntrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnEntrarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntrarKeyPressed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void txtLogUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLogUsuarioKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnEntrarActionPerformed(null);
        }
    }//GEN-LAST:event_txtLogUsuarioKeyPressed

    private void txtCadSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCadSenhaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnEntrarActionPerformed(null);
        }
    }//GEN-LAST:event_txtCadSenhaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblDuduEscudo;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblLogSenha;
    private javax.swing.JLabel lblLogUsuario;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txtCadSenha;
    private javax.swing.JTextField txtLogUsuario;
    // End of variables declaration//GEN-END:variables
}
