/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import logs.LogSessao;
import model.Usuario;
import model.Log;

/**
 *
 * @author user
 */
public class FrmTelaNivel extends javax.swing.JFrame {

    private static String nomeUsuario = "";
    private static int codUsuario;
    private static int niveisLiberados;
    static LogSessao logSessao = new LogSessao();
    Timer tempoSessao;

    /**
     * Creates new form FrmTelaNivel
     */
    public FrmTelaNivel(String usuario, int codigo, LogSessao logHerdado) {
        initComponents();
        lblArvore.setVisible(false);
        logHerdado.zeraLog();
        logSessao = logHerdado;
        nomeUsuario = usuario;
        codUsuario = codigo;

        tempoSessao = new javax.swing.Timer(1000, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                acaoTempoSessao();
            }
        });

        tempoSessao.start();





//        System.out.println(""+ logSessao.getHoraInicioSessao());
        Usuario conexao = new Usuario();
        niveisLiberados = conexao.niveisLiberados(codUsuario);
        lblBemVindo.setText("Bem Vindo " + usuario + " ! Selecione um dos 3 Níveis para jogar!");

        switch (niveisLiberados) {



            case 2:
                btnNivel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nuvensNiveis/nuvem2N.png")));
                btnNivel2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/nuvensNiveis/nuvem2C.png")));
                btnNivel2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/nuvensNiveis/nuvem2H.png")));

                break;
            case 3:
                btnNivel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nuvensNiveis/nuvem2N.png")));
                btnNivel2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/nuvensNiveis/nuvem2C.png")));
                btnNivel2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/nuvensNiveis/nuvem2H.png")));

                btnNivel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nuvensNiveis/nuvem3N.png")));
                btnNivel3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/nuvensNiveis/nuvem3C.png")));
                btnNivel3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/nuvensNiveis/nuvem3H.png")));
                break;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBemVindo = new javax.swing.JLabel();
        btnNivel1 = new javax.swing.JButton();
        btnNivel2 = new javax.swing.JButton();
        btnNivel3 = new javax.swing.JButton();
        lblArvore = new javax.swing.JLabel();
        btnDeslogar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        FundoNivel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setUndecorated(true);
        getContentPane().setLayout(null);

        lblBemVindo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblBemVindo.setText("Bem Vindo");
        getContentPane().add(lblBemVindo);
        lblBemVindo.setBounds(70, 10, 1200, 80);

        btnNivel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nuvensNiveis/nuvem1N.png"))); // NOI18N
        btnNivel1.setBorderPainted(false);
        btnNivel1.setContentAreaFilled(false);
        btnNivel1.setFocusPainted(false);
        btnNivel1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/nuvensNiveis/nuvem1C.png"))); // NOI18N
        btnNivel1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/nuvensNiveis/nuvem1H.png"))); // NOI18N
        btnNivel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNivel1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnNivel1);
        btnNivel1.setBounds(520, 450, 190, 120);

        btnNivel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nuvensNiveis/nvmdes2N.png"))); // NOI18N
        btnNivel2.setBorderPainted(false);
        btnNivel2.setContentAreaFilled(false);
        btnNivel2.setFocusPainted(false);
        btnNivel2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/nuvensNiveis/nvmdes2H.png"))); // NOI18N
        btnNivel2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/nuvensNiveis/nvmdes2C.png"))); // NOI18N
        btnNivel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNivel2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnNivel2);
        btnNivel2.setBounds(680, 330, 190, 160);

        btnNivel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nuvensNiveis/nvmdes3N.png"))); // NOI18N
        btnNivel3.setBorderPainted(false);
        btnNivel3.setContentAreaFilled(false);
        btnNivel3.setFocusPainted(false);
        btnNivel3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/nuvensNiveis/nvmdes3C.png"))); // NOI18N
        btnNivel3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/nuvensNiveis/nvmdes3H.png"))); // NOI18N
        btnNivel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNivel3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnNivel3);
        btnNivel3.setBounds(400, 290, 200, 160);

        lblArvore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/arvore.png"))); // NOI18N
        getContentPane().add(lblArvore);
        lblArvore.setBounds(500, 190, 282, 460);

        btnDeslogar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnDeslogarN.png"))); // NOI18N
        btnDeslogar.setBorder(null);
        btnDeslogar.setBorderPainted(false);
        btnDeslogar.setContentAreaFilled(false);
        btnDeslogar.setFocusPainted(false);
        btnDeslogar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnDeslogarC.png"))); // NOI18N
        btnDeslogar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnDeslogarH.png"))); // NOI18N
        btnDeslogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeslogarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeslogar);
        btnDeslogar.setBounds(200, 510, 250, 170);

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnSairN.png"))); // NOI18N
        btnSair.setBorder(null);
        btnSair.setBorderPainted(false);
        btnSair.setContentAreaFilled(false);
        btnSair.setFocusPainted(false);
        btnSair.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnSairC.png"))); // NOI18N
        btnSair.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnSairH.png"))); // NOI18N
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(0, 510, 200, 170);

        FundoNivel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FundoNivelNovo.png"))); // NOI18N
        getContentPane().add(FundoNivel);
        FundoNivel.setBounds(0, -30, 1340, 740);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1276)/2, (screenSize.height-681)/2, 1276, 681);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNivel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNivel1ActionPerformed
        // TODO add your handling code here:


        tempoSessao.stop();
        FrmNivel1_1 telaLv1 = new FrmNivel1_1(codUsuario, logSessao);
        telaLv1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNivel1ActionPerformed

    private void btnNivel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNivel2ActionPerformed
        // TODO add your handling code here:

        if (niveisLiberados == 1) {
            JdiMensagens msg = new JdiMensagens(this, rootPaneCheckingEnabled, "Você ainda não pode jogar o nível 2. ", "",
                    "Conclua o Nível 1, para liberar o Nível 2!");
            msg.setModal(true);
            msg.setVisible(true);

        } else {
            tempoSessao.stop();
            FrmNivel2_1 telaLv2 = new FrmNivel2_1(codUsuario, logSessao);
            telaLv2.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnNivel2ActionPerformed

    private void btnNivel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNivel3ActionPerformed
        // TODO add your handling code here:
        if (niveisLiberados == 3) {
            tempoSessao.stop();
            FrmNivel3_1 telaLv3 = new FrmNivel3_1(codUsuario, logSessao);
            telaLv3.setVisible(true);
            this.dispose();
        } else {
           JdiMensagens msg = new JdiMensagens(this, rootPaneCheckingEnabled, "Você ainda não pode jogar o nível 3. ", "",
                    "Conclua o Nível 2, para liberar o Nível 3!");
            msg.setModal(true);
            msg.setVisible(true);
        }
    }//GEN-LAST:event_btnNivel3ActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        tempoSessao.stop();
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnDeslogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeslogarActionPerformed
        // TODO add your handling code here:
        tempoSessao.stop();
        FrmLogin telaLogin = new FrmLogin();
        telaLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDeslogarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTelaNivel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTelaNivel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTelaNivel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTelaNivel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrmTelaNivel(nomeUsuario, codUsuario, logSessao).setVisible(true);
            }
        });
    }

    public void acaoTempoSessao() {
        logSessao.seg++;



        if (logSessao.seg == 60) {
            logSessao.min++;
            logSessao.seg = 0;
        }

        if (logSessao.min == 60) {
            logSessao.hor++;
        }

        if (logSessao.hor > 99) {
            logSessao.hor = 99;
        }



    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FundoNivel;
    private javax.swing.JButton btnDeslogar;
    private javax.swing.JButton btnNivel1;
    private javax.swing.JButton btnNivel2;
    private javax.swing.JButton btnNivel3;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel lblArvore;
    private javax.swing.JLabel lblBemVindo;
    // End of variables declaration//GEN-END:variables
}
