/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Sons.Sons;

/**
 *
 * @author User
 */
public class FrmTelaOpcao extends javax.swing.JFrame {
    private boolean tocarmusica = false;
    static Sons sfx = new Sons();
    

    /**
     * Creates new form FrmTelaOpcao
     */
    public FrmTelaOpcao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDudu = new javax.swing.JLabel();
        btnJogar = new javax.swing.JButton();
        btnRanking = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnRelatorio = new javax.swing.JButton();
        btnCadastrese1 = new javax.swing.JButton();
        lblFotoDudu = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblVersão = new javax.swing.JLabel();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setUndecorated(true);
        getContentPane().setLayout(null);

        lblDudu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lblDuduLibras.png"))); // NOI18N
        getContentPane().add(lblDudu);
        lblDudu.setBounds(70, 90, 780, 160);

        btnJogar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnLogarN.png"))); // NOI18N
        btnJogar.setBorder(null);
        btnJogar.setBorderPainted(false);
        btnJogar.setContentAreaFilled(false);
        btnJogar.setFocusPainted(false);
        btnJogar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnLogarC.png"))); // NOI18N
        btnJogar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnLogarH.png"))); // NOI18N
        btnJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJogarActionPerformed(evt);
            }
        });
        getContentPane().add(btnJogar);
        btnJogar.setBounds(500, 310, 200, 170);

        btnRanking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnRankingN.png"))); // NOI18N
        btnRanking.setBorder(null);
        btnRanking.setBorderPainted(false);
        btnRanking.setContentAreaFilled(false);
        btnRanking.setFocusPainted(false);
        btnRanking.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnRankingC.png"))); // NOI18N
        btnRanking.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnRankingH.png"))); // NOI18N
        btnRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRankingActionPerformed(evt);
            }
        });
        getContentPane().add(btnRanking);
        btnRanking.setBounds(980, 520, 270, 190);

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnSairN.png"))); // NOI18N
        btnSair.setBorder(null);
        btnSair.setBorderPainted(false);
        btnSair.setContentAreaFilled(false);
        btnSair.setFocusPainted(false);
        btnSair.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnSairC.png"))); // NOI18N
        btnSair.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnSairH.png"))); // NOI18N
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(0, 540, 200, 170);

        btnRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnRelatN.png"))); // NOI18N
        btnRelatorio.setBorder(null);
        btnRelatorio.setBorderPainted(false);
        btnRelatorio.setContentAreaFilled(false);
        btnRelatorio.setFocusPainted(false);
        btnRelatorio.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnRelatC.png"))); // NOI18N
        btnRelatorio.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnRelatH.png"))); // NOI18N
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });
        getContentPane().add(btnRelatorio);
        btnRelatorio.setBounds(230, 530, 270, 190);

        btnCadastrese1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnCadastroN.png"))); // NOI18N
        btnCadastrese1.setBorder(null);
        btnCadastrese1.setBorderPainted(false);
        btnCadastrese1.setContentAreaFilled(false);
        btnCadastrese1.setFocusPainted(false);
        btnCadastrese1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnCadastroC.png"))); // NOI18N
        btnCadastrese1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnCadastroH.png"))); // NOI18N
        btnCadastrese1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrese1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrese1);
        btnCadastrese1.setBounds(560, 530, 270, 190);

        lblFotoDudu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/duduzinho.png"))); // NOI18N
        getContentPane().add(lblFotoDudu);
        lblFotoDudu.setBounds(850, 0, 250, 590);

        jButton1.setBackground(new java.awt.Color(0, 255, 255));
        jButton1.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jButton1.setText("Tocar/Parar Música");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 30, 190, 30);

        lblVersão.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblVersão.setForeground(new java.awt.Color(255, 255, 255));
        lblVersão.setText("Versão 4.5");
        getContentPane().add(lblVersão);
        lblVersão.setBounds(100, 240, 100, 30);

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundonovo.png"))); // NOI18N
        getContentPane().add(lblFundo);
        lblFundo.setBounds(0, 0, 1380, 720);

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRankingActionPerformed
           // ao clikar no botao ira abrir a tela de cadastro

        FrmRanking ranking = new FrmRanking();
        ranking.setVisible(true);
        this.dispose();
                
    }//GEN-LAST:event_btnRankingActionPerformed

    private void btnJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJogarActionPerformed
        //ao clikar no botao ira abrir a tela de login

        FrmLogin telaLogin;
        telaLogin = new FrmLogin();
        telaLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnJogarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnCadastrese1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrese1ActionPerformed
        // TODO add your handling code here:
        
        FrmCadastro cad = new FrmCadastro();
        cad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCadastrese1ActionPerformed

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        // TODO add your handling code here:
       FrmRelatorio relat = new FrmRelatorio();
       relat.setVisible(true);
       
       this.dispose();
    }//GEN-LAST:event_btnRelatorioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if (tocarmusica == false) {
            
            sfx.tocarMusica();
            tocarmusica = true;
        }
        else {
            sfx.pararMusica();
            tocarmusica = false;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTelaOpcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTelaOpcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTelaOpcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTelaOpcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrmTelaOpcao().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrese1;
    private javax.swing.JButton btnJogar;
    private javax.swing.JButton btnRanking;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblDudu;
    private javax.swing.JLabel lblFotoDudu;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblVersão;
    // End of variables declaration//GEN-END:variables
}
