/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Aluno
 */
public class JdiAjuda extends javax.swing.JDialog {
private  static int frmNivel;
    /**
     * Creates new form JdiAjuda
     */
    public JdiAjuda(java.awt.Frame parent, boolean modal, int form) {
        super(parent, modal);
        initComponents();
        frmNivel = form;
        
        switch (frmNivel) {
            case 1:
                lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ajuda/nivel11.jpg")));
                break;
            case 2:
                lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ajuda/atv11.png")));
                break;
            case 3:
                lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ajuda/nivel12.png")));
                break;
            case 4:
                lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ajuda/atv12.png")));
                break;
            case 5:
                lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ajuda/nivel21.png")));
                break;
            case 6:
                lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ajuda/atv21.png")));
                break;
            case 7:
                lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ajuda/nivel22.png")));
                break;
            case 8:
                lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ajuda/atv22.png")));
            case 9:
                lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ajuda/nivel31.png")));
                break;
            case 10:
                lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ajuda/atv31.png")));
                break;
                
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnVoltarN.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnVoltarC.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnVoltarH.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 480, 190, 180);

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ajuda/nivel11.jpg"))); // NOI18N
        getContentPane().add(lblFundo);
        lblFundo.setBounds(0, 0, 1280, 730);

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JdiAjuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JdiAjuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JdiAjuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JdiAjuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JdiAjuda dialog = new JdiAjuda(new javax.swing.JFrame(), true, frmNivel);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblFundo;
    // End of variables declaration//GEN-END:variables
}
