/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.event.KeyEvent;

/**
 *
 * @author Luiz
 */
public class JdiMensagens extends javax.swing.JDialog {
    private static String linha1, linha2, linha3;

    /**
     * Creates new form JdiMensagens
     */
    public JdiMensagens(java.awt.Frame parent, boolean modal, String msg1, String msg2, String msg3) {
        super(parent, modal);
        linha1 = msg1; linha2 = msg2; linha3 = msg3;
        initComponents();
        this.setBackground(new Color(255,255,255,0));
        
        lblLinha1.setText(linha1);
        lblLinha2.setText(linha2);
        lblLinha3.setText(linha3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOk = new javax.swing.JButton();
        lblLinha2 = new javax.swing.JLabel();
        lblLinha3 = new javax.swing.JLabel();
        lblLinha1 = new javax.swing.JLabel();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(747, 156));
        setUndecorated(true);
        getContentPane().setLayout(null);

        btnOk.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnOK.png"))); // NOI18N
        btnOk.setText("OK");
        btnOk.setBorderPainted(false);
        btnOk.setContentAreaFilled(false);
        btnOk.setFocusPainted(false);
        btnOk.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnOKC.png"))); // NOI18N
        btnOk.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/btnOKH.png"))); // NOI18N
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        btnOk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnOkKeyPressed(evt);
            }
        });
        getContentPane().add(btnOk);
        btnOk.setBounds(500, 80, 110, 70);

        lblLinha2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        getContentPane().add(lblLinha2);
        lblLinha2.setBounds(30, 60, 530, 30);

        lblLinha3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        getContentPane().add(lblLinha3);
        lblLinha3.setBounds(30, 90, 460, 30);

        lblLinha1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        getContentPane().add(lblLinha1);
        lblLinha1.setBounds(30, 30, 530, 30);

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/balaoDudu_1.png"))); // NOI18N
        getContentPane().add(lblFundo);
        lblFundo.setBounds(0, 0, 720, 160);

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnOkKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnOkKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnOkActionPerformed(null);
        }
        
        
    }//GEN-LAST:event_btnOkKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JdiMensagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JdiMensagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JdiMensagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JdiMensagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                JdiMensagens dialog = new JdiMensagens(new javax.swing.JFrame(), true, linha1, linha2, linha3);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblLinha1;
    private javax.swing.JLabel lblLinha2;
    private javax.swing.JLabel lblLinha3;
    // End of variables declaration//GEN-END:variables
}
